-- A third data scope: the linked employee's own UNIT, and everything under it.
--
-- WHY. `dataScope` could say "the whole company" or "one person's own rows" and
-- nothing in between, so the one account shape this portal actually has most of
-- — a ROP, the head of a fifteen-strong sales team — could not be served. Given
-- ALL they read every other team's money; given OWN they read a board with one
-- row on it. The client asked for the middle in their own words: «ROP Asliddin
-- bersam shu faqat uzini malumotlarini korishi kerak umumiy emas».
--
-- ADDITIVE, AND SAFE TO APPLY AHEAD OF THE CODE. No column changes, no
-- backfill, no row is rewritten: every existing account keeps the scope it has,
-- and TEAM only exists once an administrator picks it. Applying this in the
-- PRE_DEPLOY job while the previous container is still serving is therefore
-- fine — nothing can be reading a value nothing has written yet.
--
-- ROLLING THE CODE BACK IS NOT SYMMETRIC, AND THAT IS WORTH KNOWING BEFORE
-- SOMEBODY NEEDS IT. Postgres cannot DROP an enum value, so the type keeps
-- TEAM either way; the asymmetry is on the client. Prisma validates enum
-- columns against its OWN generated enum and REFUSES a value it does not know
-- — measured on 7.9.1: P2023, «Value not found in enum», from both findUnique
-- and findMany, never a null and never a fallback. So a build from before this
-- change cannot read a user row that says TEAM at all: those accounts get a
-- 500 on every request, and `listUsers()` — one findMany over every user —
-- takes the whole /users screen down with them.
--
-- The order to undo this in, therefore: set every TEAM account back to OWN
--   UPDATE "user" SET "dataScope" = 'OWN' WHERE "dataScope" = 'TEAM';
-- and only then deploy the older build. While no account is TEAM, a rollback
-- costs nothing.
--
-- The same asymmetry applies to `session.ts`'s "an unrecognised scope degrades
-- to the narrower" guard: it is real defence against the TypeScript union
-- drifting from the Prisma enum, and it is NOT what protects an older client
-- from a newer enum value, because Prisma throws before that line is reached.
--
-- AFTER 'ALL', not appended, so the stored order matches the order the enum is
-- declared in (ALL, TEAM, OWN — widest to narrowest) and a later `migrate diff`
-- has nothing to say about it.
--
-- ALTER TYPE ... ADD VALUE inside a transaction is legal from PostgreSQL 12 on
-- as long as the new value is not USED in the same transaction. Prisma wraps
-- each migration in one and this file uses the value nowhere, so it applies
-- cleanly; production is 16.
ALTER TYPE "DataScope" ADD VALUE IF NOT EXISTS 'TEAM' AFTER 'ALL';
