import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

/**
 * Architectural boundaries are enforced here rather than by convention.
 *
 * The layering only holds if it is checked. A single `import { prisma }` inside
 * a React component would put database access in the browser bundle, and a
 * single `import { env }` would put the Bitrix24 webhook token there with it.
 * Code review catches that most of the time; lint catches it every time.
 */
const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,

  globalIgnores([
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated by Prisma — not ours to lint.
    "src/generated/**",
  ]),

  {
    rules: {
      // A leading underscore marks a parameter as deliberately unused. Used by
      // interface implementations that must accept an argument they ignore.
      "@typescript-eslint/no-unused-vars": [
        "warn",
        {
          argsIgnorePattern: "^_",
          varsIgnorePattern: "^_",
          caughtErrorsIgnorePattern: "^_",
        },
      ],
    },
  },

  {
    // ---- The domain layer must stay framework-free -------------------------
    // This is what lets the analytics engine be unit tested without a database
    // and lifted into a separate service later without changes.
    files: ["src/server/domain/**/*.ts"],
    rules: {
      "no-restricted-imports": [
        "error",
        {
          patterns: [
            {
              group: [
                "@prisma/client",
                "@/generated/*",
                "**/generated/prisma/*",
                "next",
                "next/*",
                "react",
                "react-dom",
                "@/server/repositories/*",
                "@/server/config/*",
                "@/server/integrations/*",
              ],
              message:
                "The domain layer must not depend on the framework, the database, " +
                "or configuration. Take what you need as a function parameter.",
            },
          ],
        },
      ],
    },
  },

  {
    // ---- Client code must never reach server internals ---------------------
    files: ["src/components/**/*.{ts,tsx}", "src/features/**/*.{ts,tsx}", "src/lib/**/*.{ts,tsx}"],
    rules: {
      "no-restricted-imports": [
        "error",
        {
          patterns: [
            {
              group: ["@/server/*", "@/server/**", "@prisma/client", "**/generated/prisma/*"],
              message:
                "Client code must not import server modules: they carry the database " +
                "URL and the Bitrix24 webhook token. Fetch from /api/v1 instead.",
            },
          ],
        },
      ],
    },
  },

  {
    // ---- Route handlers go through the repository layer --------------------
    files: ["src/app/api/**/*.ts"],
    rules: {
      "no-restricted-imports": [
        "error",
        {
          patterns: [
            {
              group: ["@prisma/client", "**/generated/prisma/client*"],
              message:
                "Route handlers must not query Prisma directly. Go through " +
                "src/server/repositories so authorisation scoping cannot be bypassed.",
            },
          ],
        },
      ],
    },
  },

  {
    // ---- DATA_SOURCE is read in exactly one place --------------------------
    // Branching on it elsewhere is what turns the Bitrix24 cutover back into a
    // rewrite. Ask the provider for its capabilities instead.
    files: ["src/**/*.{ts,tsx}"],
    ignores: [
      "src/server/config/env.ts",
      "src/server/config/providerFactory.ts",
    ],
    rules: {
      "no-restricted-syntax": [
        "error",
        {
          selector:
            "MemberExpression[object.name='env'][property.name='DATA_SOURCE']",
          message:
            "DATA_SOURCE may only be read in src/server/config/providerFactory.ts. " +
            "Elsewhere, depend on CrmProvider.capabilities or take the provider as a parameter.",
        },
      ],
    },
  },

  {
    // Tests reach across layers on purpose.
    files: ["tests/**/*.{ts,tsx}"],
    rules: {
      "no-restricted-imports": "off",
      "@typescript-eslint/no-non-null-assertion": "off",
    },
  },
]);

export default eslintConfig;
