/**
 * «RNP jadvali», line by line: the client's «СентябрРНП 26» (rows 4–445 of
 * its HTML export, 2026-09-30; rows 1–3 are the header the page draws
 * itself) as the client then reshaped it the same afternoon. HAND-KEPT from
 * that day — the list's ORDER is the page's order, and the numbers stay the
 * sheet's row ids, which `rnpSheet.ts` maps its rows to (`sheet.row`).
 *
 * The client's changes to the sheet (2026-09-30): the totals (42–44) sit
 * above «Таргет Collagen» / «Таргет Zextra» (were «Маркетинг Таргет»); «Количество
 * лид» (47) sits under «Регистрация COLLAGEN»; the Zextra registration (69–73)
 * is gone and two registration groups, «Asliddin ROP» and «Sadriddin ROP»,
 * follow «Saidaziz guruh» (ids 1001–1013, no sheet row); every ROP block opens
 * on its «План бажарилиши» beside the ROP's name and ends on its «Продажа …
 * факт1»; Саида's block, HR (335–343), the БАЗА blocks' «Конверсия % факт2»,
 * the per-ROP «Свод» (352–374) and «РОП / Регистрация / Разница» (377–379)
 * are gone; each logistics block names its ROP where the sheet wrote «Бунёд».
 *
 * Each entry: [row, label (column A), sub (column B when it holds text — the
 * person responsible, «без квал», «факт1» …), kind, bold, tone of the label
 * cell, tone of the fact cell].
 *
 *   'title'  — a band the sheet uses as a heading: text, no numbers.
 *   'value'  — a row of figures. The page fills it from the Bitrix24 row that
 *              names this sheet row (`sheet.row`); a row nobody fills is one
 *              Bitrix24 cannot supply, and it stays in place, empty and marked
 *              (the client's decision of 2026-09-30).
 *   'helper' — the sheet's own unlabelled scratch arithmetic. Shown only when
 *              a Bitrix24 row maps to it (the logistics «Отказ сумма»).
 *
 * One correction to the sheet's own text: in every ROP block the FAKT 2
 * average check (the row after «Конверция % факт2») is labelled «Средний чек
 * факт 1» there — a copy-paste slip. It reads «Средний чек факт 2» here,
 * because that is the figure the row carries.
 *
 * The tones are the sheet's colours by meaning, not by hex: the page draws
 * them with the product's own palette so they read in light and dark.
 */

export type RnpLayoutKind = 'title' | 'value' | 'helper'
export type RnpLabelTone = 'section' | 'team' | 'company' | 'brand' | 'alert' | 'plain'
export type RnpFactTone = 'fakt' | 'plan' | 'rate' | 'key' | 'money' | 'alert' | 'plain'

export type RnpLayoutRow = readonly [
  row: number,
  label: string,
  sub: string | null,
  kind: RnpLayoutKind,
  bold: boolean,
  tone: RnpLabelTone,
  fact: RnpFactTone,
]

export const RNP_SHEET_LAYOUT: readonly RnpLayoutRow[] = [
  [4, 'Маркетинг COLLAGEN', 'Хаёт', 'title', true, 'section', 'plain'],
  [5, 'Кол подпис sinolife.otziv', null, 'value', false, 'plain', 'plain'],
  [6, 'Кол подпис sinolife.uz', null, 'value', false, 'plain', 'plain'],
  [7, 'Кол подпис collagen.sinolife', null, 'value', false, 'plain', 'plain'],
  [8, 'Кол пост телеграм', null, 'value', false, 'plain', 'plain'],
  [9, 'Кол подпис tg', null, 'value', false, 'plain', 'plain'],
  [10, 'Кол сторисов общий', null, 'value', false, 'plain', 'plain'],
  [11, 'САС (мижоз нарҳи), $', null, 'value', false, 'plain', 'plain'],
  [12, 'ROMI %', null, 'value', false, 'plain', 'plain'],
  [42, 'Бюджет', null, 'value', true, 'plain', 'money'],
  [43, 'Количество лид', null, 'value', true, 'plain', 'plain'],
  [44, 'CPL $   цена лида', null, 'value', true, 'plain', 'rate'],
  [13, 'Таргет Collagen', null, 'title', true, 'section', 'plain'],
  [14, 'Бюджет Collagen', null, 'value', false, 'plain', 'money'],
  [15, 'Колич Collagen лид', null, 'value', false, 'plain', 'plain'],
  [16, 'Цена лида Collagen', null, 'value', false, 'plain', 'rate'],
  [37, 'Таргет Zextra', null, 'title', true, 'team', 'plain'],
  [38, 'Бюджет Zextra', null, 'value', false, 'plain', 'money'],
  [39, 'Колич Zextra лид', null, 'value', false, 'plain', 'plain'],
  [40, 'Цена лида Zextra', null, 'value', false, 'plain', 'rate'],
  [45, '', null, 'helper', true, 'plain', 'rate'],
  [48, 'Регистрация COLLAGEN', null, 'value', true, 'section', 'rate'],
  [47, 'Количество лид', 'Умида', 'value', false, 'plain', 'plain'],
  [49, '% квал лид', null, 'value', false, 'plain', 'rate'],
  [50, 'Sevinch guruh', 'без квал', 'value', false, 'plain', 'plain'],
  [51, '', 'квал', 'value', false, 'plain', 'plain'],
  [52, '', 'квал %', 'value', false, 'plain', 'plain'],
  [53, 'Gulzora guruh', 'без квал', 'value', false, 'plain', 'plain'],
  [54, '', 'квал', 'value', false, 'plain', 'plain'],
  [55, '', 'квал %', 'value', false, 'plain', 'plain'],
  [56, 'Aziz guruh', 'без квал', 'value', false, 'plain', 'plain'],
  [57, '', 'квал', 'value', false, 'plain', 'plain'],
  [58, '', 'квал %', 'value', false, 'plain', 'plain'],
  [59, 'Maftuna guruh', 'без квал', 'value', false, 'plain', 'plain'],
  [60, '', 'квал', 'value', false, 'plain', 'plain'],
  [61, '', 'квал %', 'value', false, 'plain', 'plain'],
  [62, 'Lola guruh', 'без квал', 'value', false, 'plain', 'plain'],
  [63, '', 'квал', 'value', false, 'plain', 'plain'],
  [64, '', 'квал %', 'value', false, 'plain', 'plain'],
  [65, 'Saidaziz guruh', 'без квал', 'value', false, 'plain', 'plain'],
  [66, '', 'квал', 'value', false, 'plain', 'plain'],
  [67, '', 'квал %', 'value', false, 'plain', 'plain'],
  [1001, 'Asliddin ROP', 'без квал', 'value', false, 'plain', 'plain'],
  [1002, '', 'квал', 'value', false, 'plain', 'plain'],
  [1003, '', 'квал %', 'value', false, 'plain', 'plain'],
  [1011, 'Sadriddin ROP', 'без квал', 'value', false, 'plain', 'plain'],
  [1012, '', 'квал', 'value', false, 'plain', 'plain'],
  [1013, '', 'квал %', 'value', false, 'plain', 'plain'],
  [75, '', null, 'helper', true, 'plain', 'rate'],
  [81, 'План бажарилиши', 'Гулзора РОП', 'value', true, 'team', 'plan'],
  [77, 'Конверция % от квал лид 📌', null, 'value', false, 'plain', 'plain'],
  [78, 'Средний чек факт 1 📌', null, 'value', false, 'plain', 'plain'],
  [79, 'Буюртма сони', null, 'value', false, 'plain', 'plain'],
  [80, 'Сумма факт 1 сум', null, 'value', false, 'plain', 'fakt'],
  [82, 'Ходим сони', null, 'value', false, 'plain', 'fakt'],
  [83, 'Сумма факт 2 сум', null, 'value', false, 'plain', 'fakt'],
  [84, 'Транзакция факт 2', null, 'value', false, 'plain', 'plain'],
  [85, 'Конверция % факт2', null, 'value', false, 'plain', 'plain'],
  [86, 'Средний чек факт 2 📌', null, 'value', false, 'plain', 'plain'],
  [88, '', null, 'helper', true, 'plain', 'rate'],
  [76, 'Продажа (первичка) факт1', null, 'value', false, 'plain', 'plain'],
  [94, 'План бажарилиши', 'Севинч РОП', 'value', true, 'team', 'plan'],
  [90, 'Конверция % от квал лид 📌', null, 'value', false, 'plain', 'plain'],
  [91, 'Средний чек факт 1 📌', null, 'value', false, 'plain', 'plain'],
  [92, 'Буюртма сони', null, 'value', false, 'plain', 'plain'],
  [93, 'Сумма факт 1 сум', null, 'value', false, 'plain', 'fakt'],
  [95, 'Ходим сони', null, 'value', false, 'plain', 'fakt'],
  [96, 'Сумма факт 2 сум', null, 'value', false, 'plain', 'fakt'],
  [97, 'Транзакция факт 2', null, 'value', false, 'plain', 'plain'],
  [98, 'Конверция % факт2', null, 'value', false, 'plain', 'plain'],
  [99, 'Средний чек факт 2 📌', null, 'value', false, 'plain', 'plain'],
  [101, '', null, 'helper', true, 'plain', 'plain'],
  [89, 'Продажа (первичка) факт1', null, 'value', false, 'plain', 'plain'],
  [107, 'План бажарилиши', 'Лола РОП', 'value', true, 'team', 'plan'],
  [103, 'Конверция % от квал лид 📌', null, 'value', false, 'plain', 'plain'],
  [104, 'Средний чек факт 1 📌', null, 'value', false, 'plain', 'plain'],
  [105, 'Буюртма сони', null, 'value', false, 'plain', 'plain'],
  [106, 'Сумма факт 1 сум', null, 'value', false, 'plain', 'fakt'],
  [108, 'Ходим сони', null, 'value', false, 'plain', 'fakt'],
  [109, 'Сумма факт 2 сум', null, 'value', false, 'plain', 'fakt'],
  [110, 'Транзакция факт 2', null, 'value', false, 'plain', 'plain'],
  [111, 'Конверция % факт2', null, 'value', false, 'plain', 'plain'],
  [112, 'Средний чек факт 2 📌', null, 'value', false, 'plain', 'plain'],
  [114, '', null, 'helper', true, 'plain', 'rate'],
  [102, 'Продажа (первичка) факт1', null, 'value', false, 'plain', 'plain'],
  [120, 'План бажарилиши', 'Саидазиз РОП', 'value', true, 'team', 'plan'],
  [116, 'Конверция % от квал лид 📌', null, 'value', false, 'plain', 'plain'],
  [117, 'Средний чек факт 1 📌', null, 'value', false, 'plain', 'plain'],
  [118, 'Буюртма сони', null, 'value', false, 'plain', 'plain'],
  [119, 'Сумма факт 1 сум', null, 'value', false, 'plain', 'fakt'],
  [121, 'Ходим сони', null, 'value', false, 'plain', 'fakt'],
  [122, 'Сумма факт 2 сум', null, 'value', false, 'plain', 'fakt'],
  [123, 'Транзакция факт 2', null, 'value', false, 'plain', 'plain'],
  [124, 'Конверция % факт2', null, 'value', false, 'plain', 'plain'],
  [125, 'Средний чек факт 2 📌', null, 'value', false, 'plain', 'plain'],
  [127, '', null, 'helper', true, 'plain', 'money'],
  [128, '', null, 'helper', true, 'plain', 'rate'],
  [115, 'Продажа (первичка) факт1', null, 'value', false, 'plain', 'plain'],
  [134, 'План бажарилиши', 'Аслиддин РОП', 'value', true, 'team', 'plan'],
  [130, 'Конверция % от квал лид 📌', null, 'value', false, 'plain', 'plain'],
  [131, 'Средний чек факт 1 📌', null, 'value', false, 'plain', 'plain'],
  [132, 'Буюртма сони', null, 'value', false, 'plain', 'plain'],
  [133, 'Сумма факт 1 сум', null, 'value', false, 'plain', 'fakt'],
  [135, 'Ходим сони', null, 'value', false, 'plain', 'fakt'],
  [136, 'Сумма факт 2 сум', null, 'value', false, 'plain', 'fakt'],
  [137, 'Транзакция факт 2', null, 'value', false, 'plain', 'plain'],
  [138, 'Конверция % факт2', null, 'value', false, 'plain', 'plain'],
  [139, 'Средний чек факт 2 📌', null, 'value', false, 'plain', 'plain'],
  [141, '', null, 'helper', true, 'plain', 'money'],
  [142, '', null, 'helper', true, 'plain', 'rate'],
  [129, 'Продажа (первичка) факт1', null, 'value', false, 'plain', 'plain'],
  [148, 'План бажарилиши', 'Садриддин РОП', 'value', true, 'team', 'plan'],
  [144, 'Конверция % от квал лид 📌', null, 'value', false, 'plain', 'plain'],
  [145, 'Средний чек факт 1 📌', null, 'value', false, 'plain', 'plain'],
  [146, 'Буюртма сони', null, 'value', false, 'plain', 'plain'],
  [147, 'Сумма факт 1 сум', null, 'value', false, 'plain', 'fakt'],
  [149, 'Ходим сони', null, 'value', false, 'plain', 'fakt'],
  [150, 'Сумма факт 2 сум', null, 'value', false, 'plain', 'fakt'],
  [151, 'Транзакция факт 2', null, 'value', false, 'plain', 'plain'],
  [152, 'Конверция % факт2', null, 'value', false, 'plain', 'plain'],
  [153, 'Средний чек факт 2 📌', null, 'value', false, 'plain', 'plain'],
  [155, '', null, 'helper', true, 'plain', 'rate'],
  [143, 'Продажа (первичка) факт1', null, 'value', false, 'plain', 'plain'],
  [161, 'План бажарилиши', 'Малика РОП - БАЗА', 'value', true, 'team', 'plan'],
  [157, 'Конверция % от дозвон 📌', null, 'value', false, 'plain', 'plain'],
  [158, 'Средний чек факт 1 📌', null, 'value', false, 'plain', 'plain'],
  [159, 'Буюртма сони', null, 'value', false, 'plain', 'plain'],
  [160, 'Сумма факт 1 сум', null, 'value', false, 'plain', 'fakt'],
  [162, 'Ходим сони', null, 'value', false, 'plain', 'fakt'],
  [163, 'Сумма факт 2 сум', null, 'value', false, 'plain', 'fakt'],
  [164, 'Транзакция факт 2', null, 'value', false, 'plain', 'plain'],
  [166, 'Средний чек факт 2 📌', null, 'value', false, 'plain', 'plain'],
  [167, 'Средний сумма за дозвон', null, 'value', false, 'plain', 'plain'],
  [169, '', null, 'helper', true, 'plain', 'rate'],
  [156, 'Продажа (база) факт1', null, 'value', false, 'plain', 'plain'],
  [175, 'План бажарилиши', 'Маржона РОП', 'value', true, 'team', 'plan'],
  [171, 'Конверция % от квал лид 📌', null, 'value', false, 'plain', 'plain'],
  [172, 'Средний чек факт 1 📌', null, 'value', false, 'plain', 'plain'],
  [173, 'Буюртма сони', null, 'value', false, 'plain', 'plain'],
  [174, 'Сумма факт 1 сум', null, 'value', false, 'plain', 'fakt'],
  [176, 'Ходим сони', null, 'value', false, 'plain', 'fakt'],
  [177, 'Сумма факт 2 сум', null, 'value', false, 'plain', 'fakt'],
  [178, 'Транзакция факт 2', null, 'value', false, 'plain', 'plain'],
  [179, 'Конверция % факт2', null, 'value', false, 'plain', 'plain'],
  [180, 'Средний чек факт 2 📌', null, 'value', false, 'plain', 'plain'],
  [182, '', null, 'helper', true, 'plain', 'rate'],
  [170, 'Продажа (первичка) факт1', null, 'value', false, 'plain', 'plain'],
  [188, 'План бажарилиши', 'Азизбек РОП', 'value', true, 'team', 'plan'],
  [184, 'Конверция % от квал лид 📌', null, 'value', false, 'plain', 'plain'],
  [185, 'Средний чек факт 1 📌', null, 'value', false, 'plain', 'plain'],
  [186, 'Буюртма сони', null, 'value', false, 'plain', 'plain'],
  [187, 'Сумма факт 1 сум', null, 'value', false, 'plain', 'fakt'],
  [189, 'Ходим сони', null, 'value', false, 'plain', 'fakt'],
  [190, 'Сумма факт 2 сум', null, 'value', false, 'plain', 'fakt'],
  [191, 'Транзакция факт 2', null, 'value', false, 'plain', 'plain'],
  [192, 'Конверция % факт2', null, 'value', false, 'plain', 'plain'],
  [193, 'Средний чек факт 2 📌', null, 'value', false, 'plain', 'plain'],
  [195, '', null, 'helper', true, 'plain', 'rate'],
  [183, 'Продажа (первичка) факт1', null, 'value', false, 'plain', 'plain'],
  [201, 'План бажарилиши', 'Мафтуна РОП', 'value', true, 'team', 'plan'],
  [197, 'Конверция % от квал лид 📌', null, 'value', false, 'plain', 'plain'],
  [198, 'Средний чек факт 1 📌', null, 'value', false, 'plain', 'plain'],
  [199, 'Буюртма сони', null, 'value', false, 'plain', 'plain'],
  [200, 'Сумма факт 1 сум', null, 'value', false, 'plain', 'fakt'],
  [202, 'Ходим сони', null, 'value', false, 'plain', 'fakt'],
  [203, 'Сумма факт 2 сум', null, 'value', false, 'plain', 'fakt'],
  [204, 'Транзакция факт 2', null, 'value', false, 'plain', 'plain'],
  [205, 'Конверция % факт2', null, 'value', false, 'plain', 'plain'],
  [206, 'Средний чек факт 2 📌', null, 'value', false, 'plain', 'plain'],
  [208, '', null, 'helper', false, 'plain', 'rate'],
  [196, 'Продажа (первичка) факт1', null, 'value', false, 'plain', 'plain'],
  [227, 'План бажарилиши', 'Ҳаёт РОП', 'value', true, 'team', 'plan'],
  [223, 'Конверция % от квал лид 📌', null, 'value', false, 'plain', 'plain'],
  [224, 'Средний чек факт 1 📌', null, 'value', false, 'plain', 'plain'],
  [225, 'Буюртма сони', null, 'value', false, 'plain', 'plain'],
  [226, 'Сумма факт 1 сум', null, 'value', false, 'plain', 'fakt'],
  [228, 'Ходим сони', null, 'value', false, 'plain', 'fakt'],
  [229, 'Сумма факт 2 сум', null, 'value', false, 'plain', 'fakt'],
  [230, 'Транзакция факт 2', null, 'value', false, 'plain', 'plain'],
  [231, 'Конверция % факт2', null, 'value', false, 'plain', 'plain'],
  [232, 'Средний чек факт 2 📌', null, 'value', false, 'plain', 'plain'],
  [234, '', null, 'helper', true, 'plain', 'rate'],
  [222, 'Продажа (первичка) факт1', null, 'value', false, 'plain', 'plain'],
  [240, 'План бажарилиши', 'Фаррух БАЗА', 'value', true, 'team', 'plan'],
  [236, 'Конверция % от дозвон 📌', null, 'value', false, 'plain', 'plain'],
  [237, 'Средний чек факт 1 📌', null, 'value', false, 'plain', 'plain'],
  [238, 'Буюртма сони', null, 'value', false, 'plain', 'plain'],
  [239, 'Сумма факт 1 сум', null, 'value', false, 'plain', 'fakt'],
  [241, 'Ходим сони', null, 'value', false, 'plain', 'fakt'],
  [242, 'Сумма факт 2 сум', null, 'value', false, 'plain', 'fakt'],
  [243, 'Транзакция факт 2', null, 'value', false, 'plain', 'plain'],
  [245, 'Средний чек факт 2 📌', null, 'value', false, 'plain', 'plain'],
  [246, 'Средний сумма за дозвон', null, 'value', false, 'plain', 'plain'],
  [235, 'Продажа (первичка) факт1', null, 'value', false, 'plain', 'plain'],
  [249, 'Продажа (первичка) факт2', 'Sinolife', 'title', true, 'company', 'plain'],
  [250, 'Буюртма сони', null, 'value', false, 'plain', 'plain'],
  [251, 'Конверция %', null, 'value', false, 'plain', 'plain'],
  [252, 'Конверция % от квал лид 📌', null, 'value', false, 'plain', 'plain'],
  [253, 'Сумма факт 2 сум', null, 'value', false, 'plain', 'plain'],
  [254, 'Средний чек факт 2 📌', null, 'value', false, 'plain', 'plain'],
  [256, '(первичка+база) факт2', 'Sinolife', 'title', true, 'company', 'plain'],
  [257, 'Продажа (успешка)', null, 'value', false, 'plain', 'fakt'],
  [258, 'Сумма факт1', null, 'value', false, 'plain', 'plain'],
  [259, 'Транзакция факт2', null, 'value', false, 'plain', 'plain'],
  [260, 'Сумма базы факт2', null, 'value', false, 'plain', 'money'],
  [261, 'Процент продаж базы', null, 'value', false, 'plain', 'fakt'],
  [262, 'Процент продаж нович', null, 'value', false, 'plain', 'plain'],
  [264, 'Склад и упаковка', 'Жавохир', 'title', true, 'section', 'plain'],
  [265, 'Жами заказ сони 📌', null, 'value', false, 'plain', 'plain'],
  [266, 'Не собран', null, 'value', false, 'plain', 'plain'],
  [267, 'Фоизи %', null, 'value', false, 'plain', 'plain'],
  [269, 'Логистика  Сумма факт1', 'Гулзора РОП', 'value', true, 'section', 'plain'],
  [270, 'Успешка сумма факт 2', null, 'value', false, 'plain', 'fakt'],
  [271, 'Успешкность % 📌', null, 'value', false, 'plain', 'plain'],
  [272, 'Отказ %', null, 'value', false, 'plain', 'plain'],
  [273, '', null, 'helper', false, 'plain', 'plain'],
  [274, 'Логистика  Сумма факт1', 'Севинч РОП', 'value', true, 'section', 'plain'],
  [275, 'Успешка сумма факт 2', null, 'value', false, 'plain', 'fakt'],
  [276, 'Успешкность % 📌', null, 'value', false, 'plain', 'plain'],
  [277, 'Отказ %', null, 'value', false, 'plain', 'plain'],
  [278, '', null, 'helper', false, 'plain', 'plain'],
  [279, 'Логистика  Сумма факт1', 'Саидазиз РОП', 'value', true, 'section', 'plain'],
  [280, 'Успешка сумма факт 2', null, 'value', false, 'plain', 'fakt'],
  [281, 'Успешкность % 📌', null, 'value', false, 'plain', 'plain'],
  [282, 'Отказ %', null, 'value', false, 'plain', 'plain'],
  [283, '', null, 'helper', true, 'plain', 'plain'],
  [284, 'Логистика  Сумма факт1', 'Лола РОП', 'value', true, 'section', 'plain'],
  [285, 'Успешка сумма факт 2', null, 'value', false, 'plain', 'fakt'],
  [286, 'Успешкность % 📌', null, 'value', false, 'plain', 'plain'],
  [287, 'Отказ %', null, 'value', false, 'plain', 'plain'],
  [288, '', null, 'helper', true, 'plain', 'plain'],
  [289, 'Логистика  Сумма факт1', 'Аслиддин РОП', 'value', true, 'section', 'plain'],
  [290, 'Успешка сумма факт 2', null, 'value', false, 'plain', 'fakt'],
  [291, 'Успешкность % 📌', null, 'value', false, 'plain', 'plain'],
  [292, 'Отказ %', null, 'value', false, 'plain', 'plain'],
  [293, '', null, 'helper', false, 'plain', 'plain'],
  [294, 'Логистика  Сумма факт1', 'Садриддин РОП', 'value', true, 'section', 'plain'],
  [295, 'Успешка сумма факт 2', null, 'value', false, 'plain', 'fakt'],
  [296, 'Успешкность % 📌', null, 'value', false, 'plain', 'plain'],
  [297, 'Отказ %', null, 'value', false, 'plain', 'plain'],
  [298, '', null, 'helper', false, 'plain', 'plain'],
  [299, 'Логистика  Сумма факт1', 'Малика РОП - БАЗА', 'value', true, 'section', 'plain'],
  [300, 'Успешка сумма факт 2', null, 'value', false, 'plain', 'fakt'],
  [301, 'Успешкность % 📌', null, 'value', false, 'plain', 'plain'],
  [302, 'Отказ %', null, 'value', false, 'plain', 'plain'],
  [303, '', null, 'helper', false, 'plain', 'plain'],
  [304, 'Логистика  Сумма факт1', 'Маржона РОП', 'value', true, 'section', 'plain'],
  [305, 'Успешка сумма факт 2', null, 'value', false, 'plain', 'fakt'],
  [306, 'Успешкность % 📌', null, 'value', false, 'plain', 'plain'],
  [307, 'Отказ %', null, 'value', false, 'plain', 'plain'],
  [308, '', null, 'helper', false, 'plain', 'plain'],
  [309, 'Логистика  Сумма факт1', 'Азизбек РОП', 'value', true, 'section', 'plain'],
  [310, 'Успешка сумма факт 2', null, 'value', false, 'plain', 'fakt'],
  [311, 'Успешкность % 📌', null, 'value', false, 'plain', 'plain'],
  [312, 'Отказ %', null, 'value', false, 'plain', 'plain'],
  [313, '', null, 'helper', false, 'plain', 'plain'],
  [314, 'Логистика  Сумма факт1', 'Шохжахон РОП', 'value', true, 'section', 'plain'],
  [315, 'Успешка сумма факт 2', null, 'value', false, 'plain', 'fakt'],
  [316, 'Успешкность % 📌', null, 'value', false, 'plain', 'plain'],
  [317, 'Отказ %', null, 'value', false, 'plain', 'plain'],
  [318, '', null, 'helper', false, 'plain', 'plain'],
  [324, 'Логистика  Сумма факт1', 'Фаррух БАЗА', 'value', true, 'section', 'plain'],
  [325, 'Успешка сумма факт 2', null, 'value', false, 'plain', 'fakt'],
  [326, 'Успешкность % 📌', null, 'value', false, 'plain', 'plain'],
  [327, 'Отказ %', null, 'value', false, 'plain', 'plain'],
  [328, '', null, 'helper', false, 'plain', 'plain'],
  [329, '', null, 'helper', false, 'plain', 'plain'],
  [330, 'Логистика  Сумма факт1', 'Мафтуна РОП', 'value', true, 'section', 'plain'],
  [331, 'Успешка сумма факт 2', null, 'value', false, 'plain', 'fakt'],
  [332, 'Успешкность % 📌', null, 'value', false, 'plain', 'plain'],
  [333, 'Отказ %', null, 'value', false, 'plain', 'plain'],
  [334, '', null, 'helper', false, 'plain', 'plain'],
  [346, 'Квал лид сони', 'ИЮЛЬ', 'value', true, 'section', 'plain'],
  [347, 'План продаж', null, 'value', true, 'plain', 'plain'],
  [348, 'ФАКТ 1', null, 'value', true, 'plain', 'plain'],
  [349, 'ФАКТ 2', null, 'value', true, 'plain', 'fakt'],
  [350, 'Бюджет', null, 'value', true, 'plain', 'rate'],
  [394, 'Коллаген проект', 'Сумма факт1', 'value', true, 'section', 'plain'],
  [395, 'Сумма факт2 (успешка)', null, 'value', false, 'plain', 'fakt'],
  [396, 'Первичка усп', null, 'value', false, 'plain', 'plain'],
  [397, 'База усп', null, 'value', false, 'plain', 'plain'],
  [398, 'Таргет бюджет', null, 'value', false, 'brand', 'plain'],
  [399, 'Кол лид', null, 'value', false, 'brand', 'plain'],
  [400, 'Квал лид', null, 'value', false, 'brand', 'plain'],
  [401, 'Квал лид %', null, 'value', false, 'brand', 'plain'],
  [402, 'Цена лида', null, 'value', false, 'brand', 'plain'],
  [403, 'Транзакция пер усп', null, 'value', false, 'brand', 'plain'],
  [404, 'Конверция от квал', null, 'value', false, 'brand', 'plain'],
  [405, 'Конверция', null, 'value', false, 'brand', 'plain'],
  [406, 'Средний чек', null, 'value', false, 'brand', 'plain'],
  [407, 'Маркетинг харажат план', null, 'value', true, 'plain', 'plan'],
  [408, 'Маркетинг харажат факт', null, 'value', true, 'plain', 'alert'],
  [409, 'Таргет бюджет', null, 'value', false, 'plain', 'plain'],
  [410, 'Таргетолог фот', null, 'value', false, 'plain', 'plain'],
  [411, 'Блогерлар', null, 'value', false, 'plain', 'plain'],
  [412, 'Нутрицолог', null, 'value', false, 'plain', 'plain'],
  [413, 'Брендфейс', null, 'value', false, 'plain', 'plain'],
  [414, 'Маркетинг харажатлар', null, 'value', false, 'plain', 'plain'],
  [415, 'Маркетинг команда', null, 'value', false, 'plain', 'plain'],
  [416, 'Маркетолог фот = 1%', null, 'value', false, 'plain', 'plain'],
  [417, 'CAC $', null, 'value', false, 'plain', 'key'],
  [418, '%', null, 'value', false, 'plain', 'key'],
  [421, 'Зехтра проект', 'Сумма факт1', 'value', true, 'section', 'plain'],
  [422, 'Сумма факт2 (успешка)', null, 'value', false, 'plain', 'fakt'],
  [423, 'Первичка усп', null, 'value', false, 'plain', 'plain'],
  [424, 'База усп', null, 'value', false, 'plain', 'plain'],
  [425, 'Таргет бюджет', null, 'value', false, 'brand', 'plain'],
  [426, 'Кол лид', null, 'value', false, 'brand', 'plain'],
  [427, 'Квал лид', null, 'value', false, 'brand', 'plain'],
  [428, 'Квал лид %', null, 'value', false, 'brand', 'plain'],
  [429, 'Цена лида', null, 'value', false, 'brand', 'plain'],
  [430, 'Транзакция пер', null, 'value', false, 'brand', 'plain'],
  [431, 'Конверция от квал', null, 'value', false, 'brand', 'plain'],
  [432, 'Конверция', null, 'value', false, 'brand', 'plain'],
  [433, 'Средний чек', null, 'value', false, 'brand', 'plain'],
  [434, 'Маркетинг харажат план', null, 'value', false, 'plain', 'plan'],
  [435, 'Маркетинг харажат факт', null, 'value', false, 'plain', 'alert'],
  [436, 'Таргет бюджет', null, 'value', false, 'plain', 'plain'],
  [437, 'Таргетолог фот', null, 'value', false, 'plain', 'plain'],
  [438, 'Блогерлар', null, 'value', false, 'plain', 'plain'],
  [439, 'Нутрицолог', null, 'value', false, 'plain', 'plain'],
  [440, 'Брендфейс', null, 'value', false, 'plain', 'plain'],
  [441, 'Маркетинг харажатлар', null, 'value', false, 'plain', 'plain'],
  [442, 'Маркетинг команда', null, 'value', false, 'plain', 'plain'],
  [443, 'Маркетолог фот = 1%', null, 'value', false, 'plain', 'plain'],
  [444, 'CAC $', null, 'value', false, 'plain', 'key'],
  [445, '%', null, 'value', false, 'plain', 'key'],
]
