/**
 * Continuous Bitrix24 synchronisation.
 *
 *     npm run bitrix:worker
 *
 * Keeps the database within about a minute of the portal, so the dashboard is
 * current without anyone pressing anything. The browser refetches on the same
 * cadence; the two together are what make an always-open screen trustworthy.
 *
 * WHAT RUNS HOW OFTEN
 * Transactional data — deals, stage history, calls, contacts — changes
 * constantly and is read every tick. Reference data — employees, departments,
 * products, pipelines, stages, sources, stores — changes a few times a month,
 * and re-reading it sixty times an hour would spend the portal's rate limit on
 * rows that are already correct. It runs on its own slower cadence and on the
 * first tick after startup.
 *
 * WHY IT IS SAFE TO RUN FOREVER
 * Every write is an upsert keyed on the source record's own id, so a tick that
 * overlaps the previous one cannot double anything. Each entity carries its own
 * watermark, advanced only after a clean run — a failed tick re-reads the same
 * window next time rather than skipping it.
 *
 * ONE AT A TIME
 * A Postgres advisory lock keeps a second worker out rather than letting it
 * race the first. Two running at once produced foreign-key rejections on call
 * records and spent twice the portal's rate limit for no extra freshness.
 *
 * The lock lives on a connection held open for the life of the process, NOT on
 * a pooled one — a pooled connection goes back to the pool the moment the
 * query returns and Postgres drops the lock with it, which looks like it works
 * and enforces nothing. Holding it on a dedicated client also means it
 * releases by itself if the process dies without cleaning up, the case a flag
 * column in a table gets wrong.
 *
 * A second copy WAITS instead of exiting. On a rolling redeploy the new worker
 * starts before the old one has finished its tick, and a worker that exits is
 * a worker the platform restarts — so exiting here would produce a restart
 * loop until the old process happened to go away. Waiting turns the same
 * situation into a few quiet seconds of overlap.
 */

import 'dotenv/config'

import { spawn } from 'node:child_process'

import { PrismaPg } from '@prisma/adapter-pg'
import { Pool } from 'pg'
import type { PoolClient } from 'pg'

import { caCertFromEnv, poolConfig } from '../src/server/db/poolConfig'

import { PrismaClient } from '../src/generated/prisma/client'
import type { SyncEntityValue } from '../src/server/domain/types'
import {
  Bitrix24CrmProvider,
  isCredentialFailure,
} from '../src/server/integrations/crm/bitrix24/Bitrix24CrmProvider'
import { createSyncHandlers } from '../src/server/integrations/crm/sync/handlers'
import { PrismaSyncStore } from '../src/server/integrations/crm/sync/PrismaSyncStore'
import { SyncEngine } from '../src/server/integrations/crm/sync/SyncEngine'
import { historyBackfillCursor } from '../src/server/integrations/crm/sync/backfill'

const DATABASE_URL = process.env.DATABASE_URL
const WEBHOOK_URL = process.env.BITRIX24_WEBHOOK_URL

if (!DATABASE_URL || !WEBHOOK_URL) {
  console.error('\n  DATABASE_URL va BITRIX24_WEBHOOK_URL kerak.\n')
  process.exit(1)
}

/** Seconds between ticks. One minute is the design point. */
const INTERVAL_SEC = Number(process.env.SYNC_INTERVAL_SEC ?? 60)

/** How many ticks between reference-data refreshes. Default: every 30 minutes. */
const REFERENCE_EVERY = Number(process.env.SYNC_REFERENCE_EVERY ?? 30)

/**
 * How many ticks between Roistat imports. Default: hourly.
 *
 * The marketing module reads a SECOND source — the client's published page,
 * not Bitrix24 — and without this it only ever refreshed when someone ran
 * `npm run roistat:import` by hand. On a deployed dashboard that means the
 * Reklama samarasi screen quietly freezes at whatever the last manual run
 * saw, which is exactly the failure the freshness panel exists to expose and
 * the one nobody notices because the page still renders numbers.
 *
 * Hourly, not every minute: the source is a 5.5 MB static page regenerated by
 * the client on their own schedule, and its sheet-fed dimensions move a few
 * times a day. Re-reading it sixty times an hour would spend bandwidth to
 * re-import bytes that did not change — the importer's own digest check
 * proves that, printing "0 changed" on a re-run.
 *
 * Set to 0 to turn it off.
 */
const ROISTAT_EVERY = Number(process.env.SYNC_ROISTAT_EVERY ?? 60)

/**
 * How many ticks between deletion sweeps. Default: 60 = hourly.
 *
 * A deletion is rare and a stale row is quiet — nobody notices until they go
 * looking for an order they removed and find it still counted. Hourly is
 * often enough that a test deal does not survive the afternoon, and rare
 * enough that the FULL pass it needs is not competing with the minute tick.
 *
 * Set to 0 to switch it off.
 */
const SWEEP_EVERY = Number(process.env.SYNC_SWEEP_EVERY ?? 60)

/**
 * How far back the stage history is re-read once, at startup. Default: 45 days.
 *
 * A LOST ARRIVAL ROW TAKES AN ORDER OFF THE BOARD AND SAYS NOTHING. The
 * Тасдиклаш queue is cohorted on the deal's entry into `C4:NEW`, so that one
 * row IS the order's membership — and until the watermark learned to rewind
 * after a skipped run (`SKIP_LOOKBACK_MS` in SyncEngine.ts), a row whose deal
 * had not been imported yet was dropped and never offered again. Measured
 * against the client's own board on 2026-09-03: 927148 and 928094 both reached
 * the queue on 31 August, both are absent from this database, and the deals
 * themselves are here — only their arrivals are missing.
 *
 * The engine fix stops new gaps. It cannot close the old ones, because the
 * portal is only ever asked for rows newer than the cursor. So the cursor is
 * wound back once per start, and the ordinary incremental pass repairs
 * whatever it finds — every write is the same idempotent upsert, so re-reading
 * a row that is already correct costs a write and changes nothing.
 *
 * FORTY-FIVE DAYS IS SIZED, NOT GUESSED. It is 76 000 of this portal's 222 000
 * history rows: about thirty batched round trips, a few seconds of reading and
 * one pass of chunked upserts. Compare the deletion sweep, which is why tick 0
 * is otherwise kept clear — that one walked 434 000 deals and took thirty
 * minutes, and with deploys landing several times a day the worker spent its
 * life in it. This is under a minute, once, and it is also a standing net: any
 * gap inside the window heals at the next restart even if some future skip
 * escapes the lookback.
 *
 * Set to 0 to switch it off.
 */
const HISTORY_BACKFILL_DAYS = Number(process.env.SYNC_HISTORY_BACKFILL_DAYS ?? 45)

/**
 * How long to wait after the portal has refused a whole tick.
 *
 * Ten minutes, flat, rather than the failure-count backoff: neither refusal
 * this covers is ours to retry out of. An `OVERLOAD_LIMIT` block lifts on the
 * portal's clock; a credential the portal no longer accepts lifts when a
 * person installs a new webhook. Asking sooner cannot shorten either — and on
 * a portal that has already blocked this integration once for sheer volume, it
 * can lengthen the first. See the tick loop for the measurements behind both.
 */
const PORTAL_PAUSE_MS = 10 * 60_000

/**
 * The heap the Roistat child is allowed, in megabytes.
 *
 * Deliberately NOT the worker's own 768 — see `runRoistatImport` for the
 * measurement that forced this. Roughly ten times the working set of the 5.5 MB
 * page it parses, and a third of the container, so parent and child together
 * cannot reach the ceiling. If the importer ever genuinely needs more it dies
 * with a JavaScript heap error naming this constant: one passenger failing
 * diagnosably, which is the whole point of it being a child process.
 */
const ROISTAT_HEAP_MB = 320

/**
 * Read on every tick — and CALLS is deliberately NOT among them.
 *
 * These four are what every screen in the product is built on: the deal, its
 * items, its stage history and the customer. A minute late on any of them is
 * a minute the confirmation queue, the sellers board and the payroll are
 * wrong, which is the whole reason this worker runs at all.
 *
 * `call_record` is read by NOTHING. `/insights/calls` went in the 2026-09-10
 * cull with the screen it fed, and `grep -rn "prisma.callRecord" src` now
 * returns the sync handler that writes it and nothing else — the only other
 * readers are a proof script and the importer's row count. So a per-minute
 * portal call was being spent on data no reader has seen since that cull, on
 * a portal that spent the afternoon of 2026-09-14 refusing us for overload —
 * and CALLS was the last entity it was still refusing.
 *
 * IT IS MOVED, NOT DELETED. The rows keep arriving with the reference pass
 * below, which is half-hourly rather than per-minute, so call history goes on
 * accumulating for whoever asks for it next and costs 1/30th of what it did.
 * Deleting the entity would throw away the history with the cost.
 */
const HOT: SyncEntityValue[] = ['CUSTOMERS', 'DEALS', 'DEAL_ITEMS', 'STAGE_HISTORY']

/** Read occasionally. Order matters — deals reference all of these. */
const REFERENCE: SyncEntityValue[] = [
  'DEPARTMENTS',
  'EMPLOYEES',
  'PRODUCTS',
  'PIPELINES',
  'STAGES',
  'SOURCES',
  'STORES',
  'STOCK',
  /*
    NOT reference data, and LAST on purpose.

    It rides this clock for the reason HOT gives above — nothing renders a
    call, so a minute's freshness buys nothing — and it goes at the end
    because its rows link to employees, customers and deals. The links are
    resolved from the DATABASE and an unresolved one is written as null, so
    the order cannot lose a row; it only decides whether a call recorded
    minutes ago finds the deal it belongs to on this pass or the next.
  */
  'CALLS',
]

const url: string = DATABASE_URL
const webhook: string = WEBHOOK_URL

function stamp(): string {
  return new Date().toISOString().slice(11, 19)
}

/**
 * Interruptible sleep.
 *
 * A plain setTimeout would hold SIGTERM for as long as the wait — up to six
 * minutes once backoff is in play — and the platform kills a container that
 * takes longer than thirty seconds to stop. `wake` is called by the signal
 * handler so shutdown is immediate whenever a tick is not in flight.
 */
let wake: () => void = () => {}

function sleep(ms: number): Promise<void> {
  return new Promise((resolve) => {
    const timer = setTimeout(finish, ms)
    wake = finish
    function finish() {
      clearTimeout(timer)
      wake = () => {}
      resolve()
    }
  })
}

/**
 * Arbitrary but fixed. Advisory locks are namespaced only by this number, so
 * it must be stable across deploys and unlikely to collide with anything else
 * using the same database.
 */
const LOCK_ID = 8_872_601

/** Seconds between attempts while another worker still holds the lock. */
const LOCK_RETRY_SEC = 10

/**
 * Take the single-worker lock, waiting for it if someone else has it.
 *
 * Returns the client the lock is held on. Keeping a reference matters: the
 * lock lives as long as that connection and not a moment longer.
 */
async function acquireLock(pool: Pool): Promise<PoolClient> {
  const client = await pool.connect()

  // Postgres cannot tell us the lock was lost, so if this connection breaks
  // we are no longer the only worker and must not keep writing.
  client.on('error', (error) => {
    console.error(`\n  ${stamp()} ✗ blokirovka ulanishi uzildi:`, error, '\n')
    process.exit(1)
  })

  let waited = false

  for (;;) {
    const { rows } = await client.query<{ locked: boolean }>(
      'SELECT pg_try_advisory_lock($1) AS locked',
      [LOCK_ID],
    )

    if (rows[0]?.locked) {
      if (waited) console.log(`  ${stamp()} blokirovka olindi — ishga tushdi.`)
      return client
    }

    if (!waited) {
      waited = true
      console.log(
        `\n  ${stamp()} boshqa worker ishlayapti — u toʻxtaguncha kutilmoqda.` +
          `\n  (Ikkitasi bir vaqtda ishlasa portal limitini ikki barobar sarflaydi.)\n`,
      )
    }

    await sleep(LOCK_RETRY_SEC * 1000)
  }
}

/**
 * The Roistat import, as a CHILD PROCESS rather than an inlined call.
 *
 * `scripts/importRoistat.ts` opens its own pool, owns its own transaction and
 * calls `process.exit(1)` on failure — a design that is right for a command
 * someone runs and fatal for a loop that must survive it. Spawning isolates
 * all three: a Roistat failure cannot exit this worker, cannot poison its
 * Prisma client, and cannot leave a half-open pool behind. The cost is one
 * process start an hour, which is nothing against a tick that already spends
 * thirty seconds waiting on Bitrix24.
 *
 * Never throws. The Bitrix sync is the worker's job; marketing is a passenger
 * and a passenger does not get to stop the vehicle.
 *
 * THE CHILD GETS ITS OWN, SMALLER HEAP — and that is what stopped this worker
 * dying seventeen times a day. See `ROISTAT_HEAP_MB`.
 */
async function runRoistatImport(): Promise<void> {
  await new Promise<void>((resolve) => {
    /*
      `env: process.env` MINUS `NODE_OPTIONS`, with the cap on argv instead.

      The platform sets NODE_OPTIONS=--max-old-space-size=768 on this worker and
      a spawned child inherits the whole environment — so a 1 024 MB container
      held TWO V8 isolates, each believing it could take 768 MB. Neither ever
      felt pressure, neither collected defensively, and neither raised a
      JavaScript OOM: the kernel got there first, which is exactly why no
      out-of-memory message was ever in any log.

      Measured on production 2026-09-14, before this change: the worker's own
      RSS is flat at 262-297 MB for a whole hour and the deletion sweep adds
      about 65 MB, while DigitalOcean's own metric caught the container at
      999.0 MB of 1 024 — during the tick-60 window, the only tick that runs the
      sweep AND this import. Fifteen restarts in 24 hours, every one beginning
      the instant CALLS finished, i.e. inside this block; twelve killed the
      container, three got through. Nothing else in the process is big enough to
      account for the difference.
    */
    const { NODE_OPTIONS: _workerHeap, ...env } = process.env

    /*
      SPAWN CAN THROW SYNCHRONOUSLY, and the header above promises it does not.

      `spawn` raises ENOMEM or EMFILE from inside this executor rather than
      through the 'error' event — and a throw here REJECTS the promise, which
      travels up the one awaited call in the tick loop that carries no catch,
      reaches `main().catch` and exits the process. Under memory pressure at
      tick 60 that is a second, quieter way for this block to kill the worker,
      punctual and tick-aligned and indistinguishable in the data from the
      kernel doing it. Caught here, the passenger fails and the vehicle
      continues, which is what the whole child-process design is for.
    */
    let child
    try {
      child = spawn(
        process.execPath,
        [`--max-old-space-size=${ROISTAT_HEAP_MB}`, '--import', 'tsx', 'scripts/importRoistat.ts'],
        {
          cwd: process.cwd(),
          env,
          stdio: ['ignore', 'pipe', 'pipe'],
        },
      )
    } catch (error) {
      console.warn(`  ${stamp()} roistat: ishga tushirib boʻlmadi — ${(error as Error).message}`)
      resolve()
      return
    }

    // The importer prints a full report; only its verdict belongs in this log.
    let tail = ''
    const keep = (chunk: Buffer) => {
      tail = (tail + chunk.toString()).slice(-2000)
    }
    child.stdout.on('data', keep)
    child.stderr.on('data', keep)

    // Shutdown must reach the child too: an orphaned importer would hold its
    // own pool open against a database the platform is about to take away.
    const onStop = () => child.kill('SIGTERM')
    process.once('SIGTERM', onStop)
    process.once('SIGINT', onStop)
    const done = (fn: () => void) => {
      process.off('SIGTERM', onStop)
      process.off('SIGINT', onStop)
      fn()
    }

    child.on('error', (error) => {
      done(() => {
        console.warn(`  ${stamp()} roistat: ishga tushmadi — ${error.message}`)
        resolve()
      })
    })

    child.on('close', (code, signal) => {
      done(() => {
        if (code === 0) {
          const changed = /(\d+)\s+ta oʻlchov oʻzgardi/.exec(tail)
          console.log(
            `  ${stamp()} roistat: ${changed ? `${changed[1]} oʻlchov yangilandi` : 'oʻzgarish yoʻq'}`,
          )
        } else if (code === null) {
          /*
            Killed by a signal — and WHICH signal is the whole diagnosis.

            SIGTERM is our own shutdown reaching the child mid-import: an
            interruption, not a failure, and logging it as one would put a red
            line in the log on every redeploy. SIGKILL is the kernel, which on a
            1 024 MB container means the memory ceiling — the death this worker
            spent seventeen restarts a day hiding behind an unnamed
            `code === null`. Naming it is how the next one is diagnosable
            without container logs nobody can read.
          */
          console.log(
            `  ${stamp()} roistat: toʻxtatildi (${signal ?? 'signalsiz'})` +
              (signal === 'SIGKILL' ? ' — xotira chegarasi boʻlishi mumkin' : '') +
              ' — keyingi tsiklda qaytadan uriniladi',
          )
        } else {
          const reason = /✗ IMPORT TOʻXTADI\s*\n\s*\n\s*(.+)/.exec(tail)
          console.warn(
            `  ${stamp()} roistat: muvaffaqiyatsiz (kod ${code})` +
              (reason ? ` — ${reason[1].trim().slice(0, 160)}` : ''),
          )
        }
        resolve()
      })
    })
  })
}

async function main() {
  // Five: one is checked out permanently to hold the advisory lock, and the
  // sync engine runs one query at a time, so the rest is headroom. The point
  // of the cap is the managed database's 22-connection ceiling, which the web
  // service and the deploy jobs also draw on.
  const pool = new Pool(poolConfig(url, { caCert: caCertFromEnv(), max: 5 }))
  const prisma = new PrismaClient({ adapter: new PrismaPg(pool) })

  const lockClient = await acquireLock(pool)

  const provider = new Bitrix24CrmProvider({
    webhookUrl: webhook,
    rateLimitRps: Number(process.env.BITRIX24_RATE_LIMIT_RPS ?? 2),
    requestTimeoutMs: Number(process.env.BITRIX24_REQUEST_TIMEOUT_MS ?? 30_000),
    callHistoryMonths: Number(process.env.BITRIX24_CALL_MONTHS ?? 1),
  })

  /*
    Held in a const, not inlined into the SyncEngine, because the deletion
    sweep below calls `deleteMissing` on the DEALS handler directly rather
    than going through the engine. See the sweep block for why.
  */
  const handlers = createSyncHandlers(prisma, 'BITRIX24')
  const dealsHandler = handlers.find((h) => h.entity === 'DEALS')

  const store = new PrismaSyncStore(prisma)

  const engine = new SyncEngine({
    provider,
    store,
    handlers,
    logger: {
      info: () => {},
      warn: (o, m) => console.warn(`  ${stamp()} ! ${m ?? ''}`, o ?? ''),
      error: (o, m) => console.error(`  ${stamp()} ✗ ${m ?? ''}`, o ?? ''),
    },
  })

  /*
    A FAILED HEALTH CHECK IS REPORTED, NOT FATAL — and that changed on
    2026-09-14, when Bitrix24 blocked its own REST API for a quarter of an
    hour («OVERLOAD_LIMIT — REST API is blocked due to overload»).

    `process.exit(1)` here turns exactly that state into a restart loop: the
    platform brings the worker back, the portal is still throttling, the
    process exits again — and every cycle pays the startup cost and issues the
    same call that is being refused, which is the last thing a portal
    complaining about load needs from us. Meanwhile nothing syncs even in the
    minute AFTER the block lifts, because the process that would have noticed
    is gone.

    The tick loop already handles a portal that will not answer: it logs, it
    counts consecutive failures and it backs off up to five minutes between
    ticks. Starting into that loop is strictly better than not starting.

    What is lost is the fast fail on a genuinely bad configuration — a
    mistyped webhook never gets a first reading. The line below still says so
    on the first line of the log, and the dashboard's own header now names the
    portal's error code (see `AlertsDto.syncError`), which is a better place
    for it than a container nobody is watching.
  */
  const health = await provider.healthCheck()
  console.log(`\n  ${health.ok ? '✓' : '✗'} ${health.detail}`)
  if (!health.ok) {
    console.warn(
      `  ${stamp()} ! portal javob bermadi — tsikl baribir boshlanadi,` +
        ' xatolar har tsiklda qayd etiladi.',
    )
  }

  /*
    WIND THE HISTORY CURSOR BACK, ONCE, BEFORE THE FIRST TICK.

    See `HISTORY_BACKFILL_DAYS`. The first ordinary incremental pass then
    re-reads the window and upserts whatever it finds, which is what repairs an
    arrival row that was skipped before the watermark learned to rewind.

    ONLY EVER BACKWARDS. A cursor already older than the window — after an
    outage, or on a database that has never synced — is left where it is:
    moving it forward here would skip everything between, which is the one
    thing this must not do.

    Failure is not fatal. A worker that cannot reach the cursor table has
    bigger problems than a backfill, and the tick loop below reports them
    properly; refusing to start over a repair would turn a degraded sync into
    no sync at all.
  */
  try {
    const cursor = await store.getCursor(provider.source, 'STAGE_HISTORY')
    const from = historyBackfillCursor(cursor, new Date(), HISTORY_BACKFILL_DAYS)
    if (from !== null) {
      await store.setCursor(provider.source, 'STAGE_HISTORY', from)
      console.log(
        `  ${stamp()} bosqich tarixi ${HISTORY_BACKFILL_DAYS} kunga qaytarildi —` +
          ' yoʻqolgan yozuvlar shu tsiklda tiklanadi.',
      )
    }
  } catch (error) {
    console.warn(`  ${stamp()} ! tarixni qaytarib boʻlmadi:`, error)
  }

  console.log(
    `  Sinxronizatsiya har ${INTERVAL_SEC}s. Maʼlumotnomalar har ${REFERENCE_EVERY} tsiklda.` +
      (ROISTAT_EVERY > 0 ? ` Roistat har ${ROISTAT_EVERY} tsiklda.` : ' Roistat oʻchirilgan.') +
      (SWEEP_EVERY > 0
        ? ` Oʻchirilganlarni tozalash har ${SWEEP_EVERY} tsiklda.`
        : ' Tozalash oʻchirilgan.') +
      '\n',
  )

  let stopping = false
  for (const signal of ['SIGINT', 'SIGTERM'] as const) {
    process.on(signal, () => {
      // Finish the tick in flight rather than leaving a half-written batch,
      // but cut short any wait — the platform allows thirty seconds to stop.
      console.log(`\n  ${stamp()} toʻxtatilmoqda…`)
      stopping = true
      wake()
    })
  }

  let tick = 0
  /**
   * Consecutive failures, for backoff.
   *
   * The portal blocks a method for about ten minutes when it decides a read
   * was too expensive. Hammering it every minute through that window keeps the
   * block alive; backing off lets it clear.
   */
  let failures = 0
  /** Whether the LAST tick was refused by the portal's own throttle. */
  let throttled = false
  /** Whether the LAST tick was refused for a credential the portal rejects. */
  let unauthorised = false

  while (!stopping) {
    const started = Date.now()
    const entities = tick % REFERENCE_EVERY === 0 ? [...REFERENCE, ...HOT] : HOT

    try {
      const results = await engine.runAll(entities, 'INCREMENTAL')
      const changed = results.reduce((sum, r) => sum + r.recordsCreated + r.recordsUpdated, 0)
      const failed = results.filter((r) => r.status === 'FAILED')

      /*
        A PORTAL THAT SAYS «TOO MUCH» IS NOT ASKED AGAIN IN A MINUTE.

        `OVERLOAD_LIMIT` and `QUERY_LIMIT_EXCEEDED` are Bitrix24 refusing the
        whole REST surface, not one entity having a bad second: on 2026-09-14
        it lasted four hours. The ordinary backoff below reaches five minutes
        after five consecutive failures, which over a block that long is
        another ~50 refused calls an hour against a counter we cannot see and
        may be feeding. There is nothing to gain by asking sooner — the block
        lifts on the portal's clock, not on ours — so a throttled tick waits
        ten minutes flat, and the dashboard says why in the header meanwhile.
      */
      throttled = results.some(
        (r) =>
          r.status === 'FAILED' &&
          (r.errorMessage?.includes('OVERLOAD_LIMIT') ||
            r.errorMessage?.includes('QUERY_LIMIT_EXCEEDED')),
      )

      /*
        A REVOKED WEBHOOK IS NOT A BAD MINUTE, AND WAITING IS NOT OPTIONAL.

        On 2026-09-15 the portal throttled at 05:50 UTC and then began
        answering `401 INVALID_CREDENTIALS` at 06:10 — the webhook was gone.
        The ordinary backoff caps at five minutes, so for the next hour this
        worker asked twelve entities for data with a credential the portal had
        already refused, roughly 240 calls an hour that could not succeed. The
        day before, that same portal had blocked the integration for four
        hours over volume, and the ticket we sent its support promised we back
        off when refused. This is the promise, kept in code.

        The clock cannot start again until a person installs a new webhook, so
        there is nothing for a tighter loop to catch. Ten minutes bounds the
        cost of being broken at roughly seventy refused calls an hour and
        still picks the new credential up inside one cycle.
      */
      unauthorised = results.some(
        (r) => r.status === 'FAILED' && isCredentialFailure(r.errorMessage),
      )

      if (failed.length > 0) {
        failures += 1
        console.warn(
          `  ${stamp()} ${failed.map((r) => r.entity).join(', ')} muvaffaqiyatsiz` +
            ` (${failures}-marta ketma-ket)`,
        )
        /*
          SAID ONCE, IN THE WORDS OF THE ACT IT NEEDS.

          «muvaffaqiyatsiz» above reads like a portal having a bad minute, and
          for every other failure it is. This one needs a person, and the log
          is the only place an operator will be looking before the client
          phones — so it names the act rather than the symptom.
        */
        if (unauthorised) {
          console.error(
            `  ${stamp()} ✗ Bitrix24 webhook rad etildi (401). Yangi webhook kerak —` +
              ` qayta urinish yordam bermaydi, ${PORTAL_PAUSE_MS / 60_000} daqiqa kutiladi.`,
          )
        }
      } else {
        failures = 0
        // Silent when nothing moved: a worker that logs every idle minute
        // buries the ticks that did something.
        if (changed > 0) {
          const detail = results
            .filter((r) => r.recordsCreated + r.recordsUpdated > 0)
            .map((r) => `${r.entity.toLowerCase()} ${r.recordsCreated + r.recordsUpdated}`)
            .join(', ')
          console.log(
            `  ${stamp()} ${changed} yozuv yangilandi — ${detail}` +
              `  (${((Date.now() - started) / 1000).toFixed(1)}s)`,
          )
        }
      }
    } catch (error) {
      failures += 1
      throttled = false
      unauthorised = false
      console.error(`  ${stamp()} ✗ tsikl xatosi:`, error)
    }

    /*
      DELETED IN BITRIX, DELETED HERE.

      An incremental run cannot do this and says so: it fetches only what
      changed since the watermark, so "not returned" means "not touched", not
      "gone". The sweep therefore needs a FULL pass, which is why it has its
      own, much slower clock — and why the dashboard showed a deal for as long
      as it existed, even after somebody deleted it in the portal.

      DEALS ALONE. `deal_item` and `deal_stage_history` are `onDelete: Cascade`
      on the deal, so they follow without a pass of their own; `calls` and
      `stage_history` have no sweeper at all and a FULL run over their 200-300
      thousand rows would be work with nothing to show for it.

      IDS ONLY, AND NEVER THROUGH THE ENGINE.

      This used to run `engine.runAll(['DEALS'], 'FULL', {sweepDeleted: true})`,
      and a FULL engine run does not just collect ids — it re-upserts every row
      it walks. That was 432 000 deals rewritten to answer a question the ID
      column alone answers: thirty to sixty minutes of write traffic on a
      1-vCPU database, with this loop blocked for all of it and no incremental
      tick running. `listDealIds` walks the same pipelines selecting only ID —
      a couple of minutes, zero writes — and `deleteMissing` is called
      directly, so the DEALS watermark is never touched by a sweep.

      NOT AT TICK 0. `tick` starts at zero and `0 % N === 0`, so this fired on
      the first tick after every start, restart and redeploy. With deploys
      landing more often than the old sweep could finish, the worker spent its
      whole life sweeping and the dashboard never saw a second minute-tick.
      Reference data still loads at tick 0 by design; this must not.

      Guarded, because `sweepByAntiJoin` refuses to delete anything when the
      source returns nothing at all, and `listDealIds` throws rather than
      returning a short read — a failed read must never empty the table.
    */
    if (SWEEP_EVERY > 0 && tick > 0 && tick % SWEEP_EVERY === 0 && !stopping && dealsHandler) {
      const sweepStarted = Date.now()
      try {
        const live = await provider.listDealIds()
        const deleted = (await dealsHandler.deleteMissing?.(live)) ?? 0
        // Logged unconditionally, including the zero. The old code logged only
        // when something was deleted, so a sweep that silently deleted nothing
        // for months was indistinguishable from one that had nothing to do.
        console.log(
          `  ${stamp()} tozalash: portalda ${live.size} bitim, ${deleted} ta oʻchirildi` +
            `  (${((Date.now() - sweepStarted) / 1000).toFixed(1)}s)`,
        )
      } catch (error) {
        // Never fatal: a failed sweep leaves stale rows, which is the state we
        // were already in. Losing the tick loop over it would be worse.
        console.warn(`  ${stamp()} tozalash muvaffaqiyatsiz: ${(error as Error).message}`)
      }
    }

    /*
      After the Bitrix tick, never instead of it: the portal sync is what the
      dashboard is judged on, and an hourly page fetch must not delay it.

      `tick > 0` for the same reason as the sweep: a five-megabyte page fetch
      on the first tick after every redeploy delays the first real sync for
      nothing — the source changes a few times a day.
    */
    if (ROISTAT_EVERY > 0 && tick > 0 && tick % ROISTAT_EVERY === 0 && !stopping) {
      await runRoistatImport()
    }

    tick += 1

    /**
     * Wait out the rest of the interval, not the whole interval.
     *
     * A tick that took forty seconds should be followed by twenty, not sixty —
     * otherwise the effective cadence drifts with how much work there was.
     */
    /*
      Backoff is a FLOOR, not an addend.

      Added to `remaining` it disappeared exactly when it was needed: a tick
      failing slowly — thirty-second portal timeouts, five entities — already
      overruns the interval, so `remaining` was negative and the sum stayed
      negative. The worker skipped its sleep entirely and hammered a portal
      that blocks an expensive method for about ten minutes, which is the one
      situation backoff exists to defuse. As a floor, a failing worker always
      waits at least its backoff; a long but SUCCESSFUL tick still starts the
      next one immediately, because `backoff` is zero when nothing failed.
    */
    const backoff =
      throttled || unauthorised
        ? PORTAL_PAUSE_MS
        : Math.min(failures, 5) * INTERVAL_SEC * 1000
    const remaining = Math.max(INTERVAL_SEC * 1000 - (Date.now() - started), backoff)

    if (remaining > 0 && !stopping) await sleep(remaining)
  }

  // Releasing the lock explicitly lets a replacement worker start at once
  // instead of waiting out the connection's own timeout.
  await lockClient.query('SELECT pg_advisory_unlock($1)', [LOCK_ID])
  lockClient.release()
  await prisma.$disconnect()
  await pool.end()
  console.log(`  ${stamp()} toʻxtadi.\n`)
}

main().catch((error) => {
  console.error('\n  Worker xatosi:', error, '\n')
  process.exit(1)
})
